### ISSUE TITLE
Suggestion: Open WebSocket connection when logging in

### ISSUE THREAD

**Issue by hydrabolt** [thefungus/discordbot#1]
I'm also a developer another type of Discord node.js Client ([see here](https://github.com/discord-js/discord.js)) and I found that a good way to speed it up rapidly is to start opening the WebSocket as the login request to get the token is made. Basically, open the WebSocket like this and then as soon as the token becomes available and the websocket is open, send the token. Saves about 500ms of time for me :)

**Comment by thefungus** [comment]
Interesting! I kinda did it the way it is now just incase the connection would close before a token was send, but I will look into this :) thanks!
